import React from 'react';

export const metadata = {
  title: "keen-keeper stats page",
  description: "Generated by create next app",
};

const StatsPage = () => {
  return (
    <div>
      this is Stats page
    </div>
  );
};

export default StatsPage;