"use client"
import { ContactContext } from '@/context/ContactProvider';
import useApps from '@/hooks/useApps';
import React, { useContext } from 'react';
import { Legend, Pie, PieChart, Tooltip } from 'recharts';

// export const metadata = {
//   title: "keen-keeper stats page",
//   description: "Generated by create next app",
// };

const StatsPage = () => {
  const { contact } = useContext(ContactContext);
  const { apps, loading } = useApps();
  console.log(apps, "apps");
  const contactLength = apps.length - contact.length;
  console.log(contactLength, contact.length, "uninstalledApps");

  const data = [
    { name: "Call", value: contact.length, fill: "#244D3F" },
    { name: "Text", value: contact.length, fill: "#7E35E1" },
    { name: "Video", value: contact.length, fill: "#37A163" },
  ];

  return (
    <div className=" my-10 shadow p-10 rounded-md border border-slate-300 container mx-auto">
      <h2 className="font-semibold text-3xl mb-16 text-center">
        Friendship Analytics
      </h2>
      <PieChart
        style={{
          width: "100%",
          maxWidth: "500px",
          maxHeight: "80vh",
          margin: "auto",
          aspectRatio: 1,
        }}
        responsive
      >
        <Pie
          data={data}
          innerRadius="80%"
          outerRadius="100%"
          // Corner radius is the rounded edge of each pie slice
          cornerRadius="50%"
          fill="#8884d8"
          // padding angle is the gap between each pie slice
          paddingAngle={5}
          dataKey="value"
          isAnimationActive={true}
        />
        <Legend />
        <Tooltip />
      </PieChart>
    </div>
  );
};

export default StatsPage;