"use client"
import { ContactContext } from '@/context/ContactProvider';
import Image from 'next/image';
import React, { useContext } from 'react';
import { toast } from 'react-toastify';
import TextImg from "@/assets/text.png"
import VideoImg from "@/assets/video.png"
import CallImg from "@/assets/call.png"

// export const metadata = {
//   title: "keen-keeper Timeline page",
//   description: "Generated by create next app",
// };

const TimelinePage = () => {
  const { contact, setContact } = useContext(ContactContext);
  console.log(contact, "contextData");

  const handleTimeline = (app) => {
    // console.log(app, "need to Deleted");


    const restApps = contact.filter((iApp) => iApp.id != app.id);
    // console.log(restApps, "restApps");

    setContact(restApps);
    toast.warning(`${app.name} is Deleted!`);
  };

  return (
    <div className="container mx-auto my-10">
      <h2 className='text-4xl font-bold'>Timeline</h2>
      {contact.length === 0 ? (
        <h2 className="font-bold text-4xl text-center my-5">
          No contact found!
        </h2>
      ) : (
        contact.map((app, ind) => {
          return (
            <div
              key={ind}
              className="flex gap-4 items-center justify-between shadow p-4 rounded-md bg-slate-100 mb-4"
            >
              <div className='flex justify-center items-center gap-4'>
                <div>
                  
                    <Image src={CallImg} alt='' width={50} height={50}></Image>
                  

                </div>
                <div>
                  <h2 className="font-semibold text-2xl"><span className='text-4xl font-semibold text-[#244D3F]'>meetup</span> with {app.name}</h2>
                  <p>Date: {app.next_due_date}</p>
                </div>

              </div>
              <button
                className="btn bg-secondary text-white"
                onClick={() => handleTimeline(app)}
              >
                Delete
              </button>
            </div>
          );
        })
      )}
    </div>
  );
};

export default TimelinePage;