import React from 'react';

export const metadata = {
  title: "keen-keeper Timeline page",
  description: "Generated by create next app",
};

const TimelinePage = () => {
  return (
    <div>
      This is timeline page
    </div>
  );
};

export default TimelinePage;