import React from 'react';
import SnoozeImg from "@/assets/snooze.png"
import DeleteImg from "@/assets/delete.png"
import ArchiveImg from "@/assets/archive.png"
import Image from 'next/image';
import ToggleButton from '@/components/apps/ToggleButton';

export const metadata = {
  title: "keen-keeper Timeline Details Page",
  description: "Generated by create next app",
};

const appsPromise = async function () {
  const res = await fetch("http://localhost:3000/data.json");
  const data = await res.json();
  return data;
};

const HomeDetailsPage = async ({ params }) => {
  const apps = await appsPromise();

  const { id } = await params;
  console.log(id, "params")

  const app = apps.find(app => app.id == id);
  console.log(app, "apps")
  return (
    <div>
      <div className='flex'>
        <div>
          <div className='card-body items-center text-center border border-gray-300 shadow-lg rounded-lg m-6'>
             <Image src={app.picture}
          alt={app.id}
          width={50}
          height={50}
          className="rounded-full" ></Image>
            <h1>{app.name}</h1>
            <div> <button className="btn btn-primary">{app.status}</button></div>

            <div className='flex gap-4 bg-green-200 font-semibold rounded-lg p-2'>{app.tags.map(
              (tag, index) => <div key={index}>
                {tag}
              </div>
            )}</div>
            <p>{app.bio}</p>
            <p>Email: {app.email}</p>
          </div>
          <div className='space-y-4 m-6'>
            <button className="btn btn-block"><Image src={SnoozeImg} alt=''></Image>Snooze 2 weeks</button>
            <button className="btn btn-block"><Image src={ArchiveImg} alt=''></Image>Archive</button>
            <button className="btn btn-block text-red-500"><Image src={DeleteImg} alt=''></Image>Delete</button>
          </div>
        </div>
        <div>
          <div className='grid grid-cols-3 gap-4 p-6'>
            <div className=' text-center border border-gray-400 shadow-lg rounded-md p-8'>
              <h1 className='text-2xl font-bold text-[#244D3F]'>{app.days_since_contact}</h1>
              <p className='text-gray-500'>Days Since Contact</p>
            </div>
            <div className='text-center border border-gray-400 shadow-lg rounded-md p-8'>
              <h1 className='text-2xl font-bold text-[#244D3F]'>{app.goal}</h1>
              <p className='text-gray-500'>Goal (Days)</p>
            </div>
            <div className='text-center border border-gray-400 shadow-lg rounded-md p-8'>
              <h1 className= 'text-2xl font-bold text-[#244D3F]'>{app.next_due_date}</h1>
              <p className='text-gray-500'>Days Since Contact</p>
            </div>
          </div>
          <div className='m-6 border border-gray-400 shadow-lg p-4 rounded-md'>
            <div className='flex justify-between'>
              <div>
                <p className='font-bold text-[#244D3F]'>Relationship Goal</p>
              </div>
              <div>
                <button className="btn">Edit</button>
              </div>
            </div>
            <p>Connect every <span className='font-bold'>{app.goal} days</span></p>
          </div>
          <div className='m-6 border border-gray-400 shadow-lg p-4 rounded-md'>
            <h2 className='font-bold text-[#244D3F]'>Quick Check-In</h2>
            <ToggleButton app={app} ></ToggleButton>
          </div>
        </div>


      </div>
    </div>
  );
};

export default HomeDetailsPage;