import Link from 'next/link';
import React from 'react';

export const metadata = {
  title: "keen-keeper not-found page",
  description: "Generated by create next app",
};

const NotFoundPage = () => {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100 px-4">
      <div className="text-center">

        <h1 className="text-7xl font-bold text-gray-800">404</h1>

        <h2 className="text-2xl md:text-3xl font-semibold text-gray-700 mt-4">
          Page Not Found
        </h2>

        <p className="text-gray-500 mt-2 mb-6">
          Sorry, the page you are looking for doesn’t exist or has been moved.
        </p>

        <Link
          href="/"
          className="inline-block px-6 py-3 text-white bg-blue-600 rounded-2xl shadow-md hover:bg-blue-700 transition duration-300"
        >
          Go Back Home
        </Link>

      </div>
    </div>
  );
};

export default NotFoundPage;