import React from 'react';

export const metadata = {
  title: "keen-keeper Timeline Details Page",
  description: "Generated by create next app",
};

const TimelineDetailsPage = async({params}) => {
  const p = await params;

  console.log(p,"params")
  return (
    <div>
      this is TimelineDetailsPage 
    </div>
  );
};

export default TimelineDetailsPage;